### ISSUE TITLE
thread 'main' panicked at 'failed to parse port: ParseIntError { kind: InvalidDigit }', src/libcore/result.rs:999:5

### ISSUE THREAD

**Issue by dreamcat4** [Philpax/borealis#9]
```sh
[id:~/.dev/borealis] master(+2/-0) ± cargo run 120 0 120
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/borealis 120 0 120`
smbus: /sys/bus/pci/devices/0000:00:1f.4
thread 'main' panicked at 'failed to parse port: ParseIntError { kind: InvalidDigit }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[id:~/.dev/borealis] master(+2/-0) 101 ± RUST_BACKTRACE=1 cargo run 120 0 120
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/borealis 120 0 120`
smbus: /sys/bus/pci/devices/0000:00:1f.4
thread 'main' panicked at 'failed to parse port: ParseIntError { kind: InvalidDigit }', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
             at /usr/src/rustc-1.36.0/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::expect
             at /usr/src/rustc-1.36.0/src/libcore/result.rs:827
  10: borealis::i2c::find_i2c_adapters
             at src/i2c.rs:53
  11: borealis::main
             at src/main.rs:35
  12: std::rt::lang_start::{{closure}}
             at /usr/src/rustc-1.36.0/src/libstd/rt.rs:64
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: std::rt::lang_start_internal
  16: std::rt::lang_start
             at /usr/src/rustc-1.36.0/src/libstd/rt.rs:64
  17: main
  18: __libc_start_main
  19: _start
[id:~/.dev/borealis] master(+2/-0) 101 ± sudo modprobe i2c-dev
[id:~/.dev/borealis] master(+2/-0) ± cargo run 120 0 120
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/borealis 120 0 120`
smbus: /sys/bus/pci/devices/0000:00:1f.4
thread 'main' panicked at 'failed to parse port: ParseIntError { kind: InvalidDigit }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[id:~/.dev/borealis] master(+2/-0) 101 ± 
```

**Comment by Fultos** [comment]
Same here :S

zorin@zorin:~/Downloads/Tools/borealis$ sudo cargo run 127 0 127
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/borealis 127 0 127`
smbus: /sys/bus/pci/devices/0000:00:14.0
i2c-sys: /dev/i2c-0
thread 'main' panicked at 'failed to locate auxiliary controller for MB Aura', src/libcore/option.rs:1036:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by justinkb** [comment]
@Fultus that's not the same error, at all

**Comment by laurinneff** [comment]
I have the same error as @Fultos (on Manjaro):
```
$ cargo run 127 0 127
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/borealis 127 0 127`
smbus: /sys/bus/pci/devices/0000:00:1f.4
thread 'main' panicked at 'failed to parse port: ParseIntError { kind: InvalidDigit }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by Yjnar** [comment]
This is what I get on Arch Linux:

$ RUST_BACKTRACE=1 cargo run 0 0 255                                                                                                  
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/borealis 0 0 255`
smbus: /sys/bus/pci/devices/0000:00:1f.4
thread 'main' panicked at 'failed to parse port: ParseIntError { kind: InvalidDigit }', src/libcore/result.rs:1084:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: core::result::Result<T,E>::expect
             at /build/rust/src/rustc-1.38.0-src/src/libcore/result.rs:879
   8: borealis::i2c::find_i2c_adapters
             at src/i2c.rs:53
   9: borealis::main
             at src/main.rs:35
  10: std::rt::lang_start::{{closure}}
             at /build/rust/src/rustc-1.38.0-src/src/libstd/rt.rs:64
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start_internal
  14: std::rt::lang_start
             at /build/rust/src/rustc-1.38.0-src/src/libstd/rt.rs:64
  15: main
  16: __libc_start_main
  17: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by Philpax** [comment]
Hi,

Sorry, I haven't worked on Borealis at all lately (busy with other stuff, unfortunately); that being said, this is an interesting issue.

Can someone who's experiencing this issue please add the following line after line 51?
`println!("{}", name_str);`

It should look like this:
```rust
        let name_str = String::from_utf8_lossy(&name_buf);
        println!("{}", name_str)
        let name_components: Vec<_> = name_str.trim().split(' ').collect();
```

This should print out what the name it's getting is, which should help me diagnose why it's in a different format. Cheers!

**Comment by dreamcat4** [comment]
Hey @Philpax seem to be empty string I am getting here

```sh
[id:~/.dev/borealis] master(+4/-0) 101 ± cargo build
   Compiling semver-parser v0.7.0
   Compiling autocfg v0.1.1
   Compiling libc v0.2.46
   Compiling nix v0.11.0
   Compiling void v1.0.2
   Compiling cfg-if v0.1.6
   Compiling rand_core v0.3.0
   Compiling bitflags v1.0.4
   Compiling byteorder v1.2.7
   Compiling rand_hc v0.1.0
   Compiling rand_xorshift v0.1.1
   Compiling rand_isaac v0.1.1
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.3
   Compiling semver v0.9.0
   Compiling rustc_version v0.2.3
   Compiling rand_os v0.1.0
   Compiling rand_pcg v0.1.1
   Compiling i2cdev v0.4.1
   Compiling borealis v0.1.0 (/home/id/Mega/dev/borealis)
warning: trait objects without an explicit `dyn` are deprecated
  --> src/aura_error.rs:39:32
   |
39 |     fn cause(&self) -> Option<&error::Error> {
   |                                ^^^^^^^^^^^^ help: use `dyn`: `dyn error::Error`
   |
   = note: #[warn(bare_trait_objects)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 5.67s
θ63° [id:~/.dev/borealis] master(+4/-0) ± cargo run 127 0 127
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/borealis 127 0 127`
smbus: /sys/bus/pci/devices/0000:00:1f.4
SMBus I801 adapter at f000

thread 'main' panicked at 'failed to parse port: ParseIntError { kind: InvalidDigit }', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[id:~/.dev/borealis] master(+4/-0) 101 ± 
```

and the same thing with the backtrace / call stack

```sh
^[[Aθ63° [id:~/.dev/borealis] master(+4/-0) 101 ± RUST_BACKTRACE=full cargo run 127 0 127
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/borealis 127 0 127`
smbus: /sys/bus/pci/devices/0000:00:1f.4
SMBus I801 adapter at f000

thread 'main' panicked at 'failed to parse port: ParseIntError { kind: InvalidDigit }', src/libcore/result.rs:999:5
stack backtrace:
   0:     0x56303d2ebc61 - std::sys_common::backtrace::print::hc37753fd01765e69
   1:     0x56303d2f0322 - std::panicking::default_hook::{{closure}}::h827f84ab19d3ba68
   2:     0x56303d2f00b3 - std::panicking::default_hook::h7a61e2fabd403e6d
   3:     0x56303d2f0960 - std::panicking::rust_panic_with_hook::hdf58d8a3e45412d2
   4:     0x56303d2f04f2 - std::panicking::continue_panic_fmt::hf338451f3b80117e
   5:     0x56303d2f03d6 - rust_begin_unwind
   6:     0x56303d3011fd - core::panicking::panic_fmt::hb47e374a5234a09c
   7:     0x56303d2c842f - core::result::unwrap_failed::h31e7b132641a9dd1
                               at /usr/src/rustc-1.37.0/src/libcore/macros.rs:18
   8:     0x56303d2c9488 - core::result::Result<T,E>::expect::h739c2aa76b62c32f
                               at /usr/src/rustc-1.37.0/src/libcore/result.rs:827
   9:     0x56303d2c0190 - borealis::i2c::find_i2c_adapters::h687076b8bfb12c05
                               at src/i2c.rs:54
  10:     0x56303d2b9bc7 - borealis::main::hbdf47012822b145b
                               at src/main.rs:35
  11:     0x56303d2c7d72 - std::rt::lang_start::{{closure}}::h1d01027db101ce68
                               at /usr/src/rustc-1.37.0/src/libstd/rt.rs:64
  12:     0x56303d2f03c3 - std::panicking::try::do_call::h78186ff532cc12a3
  13:     0x56303d2f16da - __rust_maybe_catch_panic
  14:     0x56303d2e7039 - std::rt::lang_start_internal::h54a47c0b3c8d65e6
  15:     0x56303d2c7d39 - std::rt::lang_start::h207ae370159150c4
                               at /usr/src/rustc-1.37.0/src/libstd/rt.rs:64
  16:     0x56303d2babaa - main
  17:     0x7f67125cc1e3 - __libc_start_main
  18:     0x56303d2b91ae - _start
  19:                0x0 - <unknown>
θ63° [id:~/.dev/borealis] master(+4/-0) 101 ±
```

**Comment by Philpax** [comment]
I've pushed up a commit that skips over non-PIIX4 adapters, but this might still fail if your system doesn't use PIIX4. Can you give it a shot and see what happens?

**Comment by dreamcat4** [comment]
Thank you for taking the time and looking into this. Pulled and build the latest from master, and seems to be getting a new error message now, which is:

```sh
id:~/.dev/borealis] master ± cargo run 127 0 127
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/borealis 127 0 127`
smbus: /sys/bus/pci/devices/0000:00:1f.4
thread 'main' panicked at 'failed to locate AMD system SMBus', src/libcore/option.rs:1034:5
```

The [full log is here](https://gist.github.com/dreamcat4/1b0a321cc9dc7712acb3c71a69e3e2ae).

I should also mention that this product is the: ASUS Maximus IX (or X) Apex hardware. If there is any other commands I can run to gather more information on the `i2c` / `smbus`. Very happy to do that, and delve a little deeper.

**Comment by dreamcat4** [comment]
Hey @Philpax I have just found today another project, where the intel boards are documented you can see here:

https://gitlab.com/CalcProgrammer1/OpenAuraSDK

So it's definately have to be going through the `SMBus I801 adapter at f000` as was reported back previously. According to that information over there, I need to load up some custom kernel module etc. Hopefully this clarifies the situation in regards to all of the Intel motherboards.

**Comment by Philpax** [comment]
Ah yep, I've had a quick look. Based on Adam's research, I _think_ this should be as straight-forward as simply writing to the I801 or NCT67xx (after his patch), but I don't really have an easy way of testing that.

I'm pretty busy right now, but I'll see if I can hack together something at some point in the future that isn't as tied to my particular system; hopefully everything will "just work" once it's pointed in the right direction.

Before I do that, though, I should probably chat to Adam and see how he's faring; both of our projects are doing very similar things, after all, and I don't want to step on his toes. Have you tried using OpenAuraSDK and seeing if it works for you?

**Comment by dreamcat4** [comment]
@Philpax hey sure man! I encourage you to talk to Adam over there and try to co-operate / support both each other's projects.

Even if there is some duplication of efforts, your code still can be very useful specficially as a library in rust, to support other rust programs (providing them an API for rgb control).

It is also a nice example application for rust, for people trying to get into the language a do something that is 'useful' or practical. And it gives a very pleasing interaction of seeing the RGB lights fire up / etc. Which is a great way to get hooked from that perspective of learning a new language.
